### PR TITLE
Delist Perseus Toolkit

### PR DESCRIPTION
**Pull request by mr-perseus**

### CODE REVIEW

**Comment by mr-perseus** [comment]
@xShteff One of my scripts got removed without notice. I didn't get a single ping either in a PR / DM, sorry that's unacceptable.

**Review by xShteff — APPROVED** [review]

**Comment by xShteff** [comment]
Hi @mr-perseus - I've removed a couple of userscripts but I actually given away a 2-week notice and asked their owners to remove supposed illegal features before doing so :p. I believe @thathankatw can confirm this, as one of his scripts was also removed as requested by him.

Looking at the script you removed from the list - that's actually something you chose yourself to move away from the organisation

image

**Comment by mr-perseus** [comment]
@xShteff Yeah I didn't get any notice then, but it's okay. This repo in your screenshot is actually another one I just transferred because I don't want any other repos to be randomly removed in the future.

**Comment by xShteff** [comment]
> @xShteff Yeah I didn't get any notice then, but it's okay. This repo in your screenshot is actually another one I just transferred because I don't want any other repos to be randomly removed in the future.

Fair enough, I've opened an issue in the repo and tagged the contributors.  Also GitHub allows me to restore repositories deleted up to a month or two after they were deleted btw. If you want to transfer it to yourself I can probably help you achieve that.

**Comment by mr-perseus** [comment]
> > @xShteff Yeah I didn't get any notice then, but it's okay. This repo in your screenshot is actually another one I just transferred because I don't want any other repos to be randomly removed in the future.
> 
> Fair enough, I've opened an issue in the repo and tagged the contributors. Also GitHub allows me to restore repositories deleted up to a month or two after they were deleted btw. If you want to transfer it to yourself I can probably help you achieve that.

Okay, then I probably wasn't in that group. Thanks for the help, but it's okay. I still have the repository locally, I will maybe push it to a new repo in the future. 👍

**Pull request merged**
